name: Ejecutar script de aprobaciones

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyodbc openpyxl

    - name: Ejecutar script
      run: python aprobacionesPendientes.py

